# Generated by Django 5.2 on 2025-04-13 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Введите название тега', max_length=256, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Таг',
                'verbose_name_plural': 'Таги',
            },
        ),
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Введите название типа', max_length=256, verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=256, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание продукта', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену продукта', max_digits=8, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Картинка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tag')),
            ],
            options={
                'verbose_name': 'Таг в продукте',
                'verbose_name_plural': 'Таги в продуктах',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.typeofproduct')),
            ],
            options={
                'verbose_name': 'Тип в продукте',
                'verbose_name_plural': 'Типы в продуктах',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Введите характеристику продукта', max_length=256, verbose_name='Характеристика продукта')),
                ('measurement_unit', models.TextField(verbose_name='Единицы измерения')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.typeofproduct')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
